export declare function behavior(override: any): (target: any) => void;
export declare function customElement(name: any): (target: any) => void;
export declare function customAttribute(name: any): (target: any) => void;
export declare function templateController(target?: any): any;
export declare function bindable(nameOrConfigOrTarget: any, key?: any, descriptor?: any): any;
export declare function dynamicOptions(target?: any): any;
export declare function syncChildren(property: any, changeHandler: any, selector: any): (target: any) => void;
export declare function useShadowDOM(target: any): void | ((target: any) => void);
export declare function skipContentProcessing(target: any): void | ((target: any) => void);
export declare function useView(path: any): (target: any) => void;
export declare function noView(target?: any): any;
export declare function elementConfig(target: any): void | ((target: any) => void);
