define(["require", "exports", '../metadata/index', './property', './attached-behavior', './children', './custom-element', './element-config', './template-controller', './view-strategy', './attached-behavior', './property', './resource-registry', './children', './custom-element', './element-config', './template-controller', './view-strategy', './view-compiler', './view-engine', './view-factory', './view-slot', './binding-language', './composition-engine', './animator'], function (require, exports, _index, _property, _attached_behavior, _children, _custom_element, _element_config, _template_controller, _view_strategy, _attached_behavior_1, _property_1, _resource_registry, _children_1, _custom_element_1, _element_config_1, _template_controller_1, _view_strategy_1, _view_compiler, _view_engine, _view_factory, _view_slot, _binding_language, _composition_engine, _animator) {
    exports.AttachedBehavior = _attached_behavior_1.AttachedBehavior;
    exports.BehaviorProperty = _property_1.BehaviorProperty;
    exports.OptionsProperty = _property_1.OptionsProperty;
    exports.ResourceRegistry = _resource_registry.ResourceRegistry;
    exports.ViewResources = _resource_registry.ViewResources;
    exports.ChildObserver = _children_1.ChildObserver;
    exports.CustomElement = _custom_element_1.CustomElement;
    exports.UseShadowDOM = _custom_element_1.UseShadowDOM;
    exports.SkipContentProcessing = _custom_element_1.SkipContentProcessing;
    exports.ElementConfig = _element_config_1.ElementConfig;
    exports.TemplateController = _template_controller_1.TemplateController;
    exports.ViewStrategy = _view_strategy_1.ViewStrategy;
    exports.UseView = _view_strategy_1.UseView;
    exports.ConventionalView = _view_strategy_1.ConventionalView;
    exports.NoView = _view_strategy_1.NoView;
    exports.ViewCompiler = _view_compiler.ViewCompiler;
    exports.ViewEngine = _view_engine.ViewEngine;
    exports.ViewFactory = _view_factory.ViewFactory;
    exports.BoundViewFactory = _view_factory.BoundViewFactory;
    exports.ViewSlot = _view_slot.ViewSlot;
    exports.BindingLanguage = _binding_language.BindingLanguage;
    exports.CompositionEngine = _composition_engine.CompositionEngine;
    exports.Animator = _animator.Animator;
    exports.Behavior = _index.Metadata;
    exports.Behaviour = _index.Metadata;
    _index.Metadata.configure.classHelper('withProperty', _property.BehaviorProperty);
    _index.Metadata.configure.classHelper('withOptions', _property.OptionsProperty);
    _index.Metadata.configure.classHelper('attachedBehavior', _attached_behavior.AttachedBehavior);
    _index.Metadata.configure.classHelper('syncChildren', _children.ChildObserver);
    _index.Metadata.configure.classHelper('customElement', _custom_element.CustomElement);
    _index.Metadata.configure.classHelper('useShadowDOM', _custom_element.UseShadowDOM);
    _index.Metadata.configure.classHelper('elementConfig', _element_config.ElementConfig);
    _index.Metadata.configure.classHelper('templateController', _template_controller.TemplateController);
    _index.Metadata.configure.classHelper('useView', _view_strategy.UseView);
    _index.Metadata.configure.classHelper('noView', _view_strategy.NoView);
    _index.Metadata.configure.classHelper('skipContentProcessing', _custom_element.SkipContentProcessing);
});
